export default {
  earth: require("../../../assets/images/guide/earth.png"),
  grain: require("../../../assets/images/stickers/grain.png"),
  vitamina: require("../../../assets/images/stickers/vitamina.png"),
  dessert: require("../../../assets/images/stickers/dessert.png"),
  bread: require("../../../assets/images/stickers/bread.jpeg"),
  freshfood: require("../../../assets/images/stickers/freshfood.png"),
  dairy: require("../../../assets/images/stickers/dairy.png"),
  eggs: require("../../../assets/images/stickers/eggs.png"),
  otherfruit: require("../../../assets/images/stickers/otherfruit.png"),
  legumes: require("../../../assets/images/stickers/legumes.png"),
  nuts: require("../../../assets/images/stickers/nuts.png"),
  budget: require("../../../assets/images/stickers/budget.png"),
  favorite: require("../../../assets/images/stickers/favorite.png"),
  add: require("../..//\../assets/images/stickers/add.png"),
  recipes: require("../../../assets/images/stickers/recipes.png"),
  setting: require("../../../assets/images/stickers/setting.png"),
  breakfast: require("../../../assets/images/stickers/breakfast.png"),
  morningtea: require("../../../assets/images/stickers/morningtea.png"), 
  lunch: require("../../../assets/images/stickers/lunch.png"),
  afternoontea: require("../../../assets/images/stickers/afternoontea.png"),
  supper: require("../../../assets/images/stickers/supper.png"),
  eveningsnack: require("../../../assets/images/stickers/eveningsnack.png"),
  spinach: require("../../../assets/images/stickers/spinach.png"),
  yogurt: require("../../../assets/images/stickers/yogurt.jpeg"),
};
